# Generated by Django 2.1.7 on 2019-03-13 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=80)),
                ('curso', models.CharField(choices=[('C', 'Computacao'), ('M', 'Mecanica'), ('X', 'Mecatronica')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao', models.CharField(max_length=200)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('abreviacao', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='opcao',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Projeto'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='opcoes',
            field=models.ManyToManyField(through='projetos.Opcao', to='projetos.Projeto'),
        ),
    ]
