# Generated by Django 2.1.7 on 2019-03-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcao',
            name='prioridade',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
