# Generated by Django 2.1.7 on 2019-03-18 02:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_opcao_prioridade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('nome_empresa', models.CharField(max_length=80)),
                ('sigla', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='login',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Empresa'),
        ),
    ]
