# Generated by Django 2.1.7 on 2019-03-18 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_auto_20190318_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=80)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Empresa')),
            ],
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=80),
        ),
    ]
