# Generated by Django 2.1.7 on 2019-03-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_auto_20190318_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='id',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='login',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='login',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='login',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='abreviacao',
            field=models.CharField(help_text='Abreviacao usada para o projeto', max_length=10),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.CharField(help_text='Descricao do projeto', max_length=200),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(help_text='Titulo do Projeto', max_length=100),
        ),
    ]
