# Generated by Django 2.1.7 on 2019-03-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_auto_20190319_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='id',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='login',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
