# Generated by Django 2.1.7 on 2019-03-20 00:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_auto_20190319_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome_completo']},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['sigla']},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['abreviacao']},
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='email_pessoal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('C', 'Computacao'), ('M', 'Mecanica'), ('X', 'Mecatronica')], help_text='Curso Matriculado', max_length=1),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID para opcao de projeto', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(help_text='Descricao do projeto', max_length=1000),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID para projeto', primary_key=True, serialize=False),
        ),
    ]
