# Generated by Django 2.1.7 on 2019-03-21 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_auto_20190319_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ano',
            field=models.PositiveIntegerField(default=2018, help_text='Ano que o projeto comeca', validators=[django.core.validators.MinValueValidator(2018), django.core.validators.MaxValueValidator(3018)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='semestre',
            field=models.PositiveIntegerField(default=2, help_text='Semestre que o projeto comeca', validators=[django.core.validators.MinValueValidator(2018), django.core.validators.MaxValueValidator(3018)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_completo',
            field=models.CharField(help_text='Nome completo do aluno', max_length=80),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='opcoes',
            field=models.ManyToManyField(help_text='Opcoes de projeto escolhidos', through='projetos.Opcao', to='projetos.Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(help_text='Titulo do projeto', max_length=100),
        ),
    ]
