# Generated by Django 2.1.7 on 2019-03-22 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0009_auto_20190321_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='disponivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projeto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
