# Generated by Django 2.1.7 on 2019-03-23 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0010_auto_20190321_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcao',
            options={'ordering': ['prioridade']},
        ),
        migrations.AlterField(
            model_name='projeto',
            name='semestre',
            field=models.PositiveIntegerField(help_text='Semestre que o projeto comeca', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
