# Generated by Django 2.1.7 on 2019-03-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0011_auto_20190322_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['sigla'], 'permissions': (('altera_empresa', 'altera_professor'),)},
        ),
    ]
