# Generated by Django 2.1.7 on 2019-03-23 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0013_auto_20190322_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome'], 'permissions': (('altera_empresa', 'altera_professor'),)},
        ),
    ]
