# Generated by Django 2.1.7 on 2019-03-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0014_auto_20190322_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['sigla'], 'permissions': (('altera_empresa', 'Empresa altera valores'), ('altera_professor', 'Professor altera valores'))},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['abreviacao'], 'permissions': (('altera_empresa', 'Empresa altera valores'), ('altera_professor', 'Professor altera valores'))},
        ),
    ]
