# Generated by Django 2.1.7 on 2019-03-23 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0015_auto_20190322_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome_completo'], 'permissions': (('altera_professor', 'Professor altera valores'),)},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome'], 'permissions': (('altera_empresa', 'Empresa altera valores'), ('altera_professor', 'Professor altera valores'))},
        ),
        migrations.AlterModelOptions(
            name='opcao',
            options={'ordering': ['prioridade'], 'permissions': (('altera_professor', 'Professor altera valores'),)},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['nome'], 'permissions': (('altera_professor', 'Professor altera valores'),)},
        ),
    ]
