# Generated by Django 2.1.7 on 2019-03-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0017_aluno_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nascimento',
            field=models.DateField(),
        ),
    ]
