# Generated by Django 2.2.25 on 2022-02-01 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Data e hora do relato')),
                ('texto', models.TextField(blank=True, help_text='Texto do relato', max_length=1000, null=True, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Relato',
                'verbose_name_plural': 'Relatos',
                'ordering': ['momento', 'alocacao'],
            },
        ),
    ]
