# Generated by Django 2.2.25 on 2022-02-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('estudantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relato',
            name='alocacao',
            field=models.ForeignKey(blank=True, help_text='relacao de alocação entre projeto e estudante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeto_alocado_relato', to='users.Alocacao'),
        ),
    ]
