# Generated by Django 2.2.13 on 2020-12-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudantes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entidade',
        ),
    ]
