# Generated by Django 2.2.25 on 2022-01-26 18:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('estudantes', '0002_delete_entidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Data e hora da comunicação')),
                ('texto', models.TextField(blank=True, help_text='Texto do relato', max_length=1000, null=True, verbose_name='Texto')),
                ('alocacao', models.ForeignKey(blank=True, help_text='relacao de alocação entre projeto e estudante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeto_alocado_relato', to='users.Alocacao')),
            ],
            options={
                'verbose_name': 'Relato',
                'verbose_name_plural': 'Relatos',
                'ordering': ['momento', 'alocacao'],
            },
        ),
    ]
